server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: ise-recommond
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/tj?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
mybatis:
  mapperLocations: classpath:mapper/*.xml
